export default {
    ADD_FAV : 'ADD_FAV',
    REMOVE_FAV: 'REMOVE_FAV',
    UPDATE_CURRENT_CAR: 'UPDATE_CURRENT_CAR',
    UPDATE_CURRENT_PAGE: 'UPDATE_CURRENT_PAGE',
    UPDATE_PAGE_COUNT: 'UPDATE_PAGE_COUNT',
    FILTER_BY_MANUFACTURER: 'FILTER_BY_MANUFACTURER',
    FILTER_BY_COLOR: 'FILTER_BY_COLOR',
    UPDATE_PAGE_CARS: 'UPDATE_PAGE_CARS',
    UPDATE_SORT: 'UPDATE_SORT'
}